version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: vehicle
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: abcd1234
    ports:
      - "5432:5432"